kumuluzee:
  name: stream-service
  env:
    name: prod
  version: 1.0.0
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 20
    ping-interval: 15
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 30
    checks:
      disk-space-health-check:
        threshold: 100000000
      mongo-health-check:
        connection-url: mongodb://ec2-52-214-16-215.eu-west-1.compute.amazonaws.com:27017/rso-streams?serverSelectionTimeoutMS=2000
  metrics:
    web-instrumentation:
      - name: metricsEndpoint
        url-pattern: /metrics/*
      - name: streamsEndpoint
        url-pattern: /v1/streams/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="streams">
                      <Appenders>
                          <Socket name="logstash" host="1b343a4b-9fcf-48d4-a992-5e8a44323bff-ls.logit.io" port="14583" protocol="tcp">
                              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                          </Socket>
                      </Appenders>
                      <Loggers>
                          <!-- Resources (REST) -->
                          <Logger name="com.rso.stream.resources.StreamResource" level="trace" additivity="false">
                              <AppenderRef ref="logstash"/>
                          </Logger>

                          <Root level="all">
                              <AppenderRef ref="console" level="info"/>
                          </Root>
                      </Loggers>
                  </Configuration>'

config-properties:
  mongoUrl: ec2-52-214-16-215.eu-west-1.compute.amazonaws.com
  mongoDatabase: rso-streams